# Generated by Django 4.2.6 on 2023-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_menu_museum_visit_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
