# Generated by Django 4.2.6 on 2023-10-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_museum_name_en_museum_name_ru_museum_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='address_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='address_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='address_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='description_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='description_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
