# Generated by Django 4.2.6 on 2023-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_museum_address_en_museum_address_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description_en',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description_ru',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description_uz',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
