# Generated by Django 4.2.5 on 2023-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_alter_museum_description_alter_museum_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description_en',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description_ru',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description_uz',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
