# Generated by Django 4.2.5 on 2023-10-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_alter_museum_description_alter_museum_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
